export const DI_TRANSACTION_REPOSITORY = 'DI_TRANSACTION_REPOSITORY';
export const DI_USER_INTEGRATION_SERVICE = 'DI_USER_INTEGRATION_SERVICE';
export const DI_MESSAGE_PRODUCER_SERVICE = 'DI_MESSAGE_PRODUCER_SERVICE';