version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bank-transactions-container
    environment:
      POSTGRES_DB: bank-transactions-database
      POSTGRES_USER: bank-transactions-user
      POSTGRES_PASSWORD: bank-transactions-password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: bank-transactions-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq-definitions.json:/etc/rabbitmq/definitions.json
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

volumes:
  postgres_data:
  rabbitmq_data:
